import java.sql.DriverManager;
var url = "jdbc:sqlserver://localhost:1433;databaseName=AgroPacayales;encrypt=true;trustServerCertificate=true";
var user = "sa";
var pass = "Admin12345!";
var conn = DriverManager.getConnection(url, user, pass);
var stmt = conn.createStatement();
stmt.executeUpdate("ALTER TABLE supplier ADD created_date date NULL, credit_limit float NULL");
System.out.println("ALTER TABLE executed");
stmt.close();
conn.close();
